### ISSUE TITLE
Putting tags on decoders

### ISSUE THREAD

**Issue by Samiod131** [maxtremblay/pyqec#3]
It would  be important to call different decoders for experiments. Putting tags would be necessary.

**Comment by maxtremblay** [comment]
Done. This is now in version 0.6.0.

You can do something like this

```python
class Decoder:
    def __init__(self, some_parameter):
        self.some_parameter
        
    def decoder(self, message):
        ...
        
    def tag(self):
        return f"DECODER({self.some_parameter})"
```

Basically, if the "tag(self)" method exists and returns a non-empty string, it will be used as a tag.
